"""add_calendar_system_tables

Revision ID: 929b441e05e8
Revises: 01b91f533f24
Create Date: 2026-10-02 18:14:49.824173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '929b441e05e8'
down_revision: Union[str, Sequence[str], None] = '01b91f533f24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subjects_code'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_id'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_programs_id'), table_name='programs')
    op.drop_index(op.f('ix_programs_name'), table_name='programs')
    op.drop_table('programs')
    op.drop_index(op.f('ix_teacher_busy_slots_id'), table_name='teacher_busy_slots')
    op.drop_index(op.f('ix_teacher_busy_slots_teacher_short_name'), table_name='teacher_busy_slots')
    op.drop_table('teacher_busy_slots')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_busy_slots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('teacher_short_name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('scope', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('day_of_week', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('specific_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('teacher_busy_slots_pkey'))
    )
    op.create_index(op.f('ix_teacher_busy_slots_teacher_short_name'), 'teacher_busy_slots', ['teacher_short_name'], unique=False)
    op.create_index(op.f('ix_teacher_busy_slots_id'), 'teacher_busy_slots', ['id'], unique=False)
    op.create_table('programs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('semesters_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('programs_pkey'))
    )
    op.create_index(op.f('ix_programs_name'), 'programs', ['name'], unique=True)
    op.create_index(op.f('ix_programs_id'), 'programs', ['id'], unique=False)
    op.create_table('subjects',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('program', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('semester', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('entry_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('weekly_hours', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('subjects_pkey'))
    )
    op.create_index(op.f('ix_subjects_id'), 'subjects', ['id'], unique=False)
    op.create_index(op.f('ix_subjects_code'), 'subjects', ['code'], unique=False)
    # ### end Alembic commands ###
